"""New Instruction and Ingredient table, deleted instruction and ingredient columns

Revision ID: 1cd8d27e3863
Revises: 0bc4ef7fd568
Create Date: 2025-07-28 21:31:01.990036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd8d27e3863'
down_revision: Union[str, Sequence[str], None] = '0bc4ef7fd568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruction',
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('recipe', 'instructions')
    op.drop_column('recipe', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('ingredients', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('recipe', sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('instruction')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
