"""changes to set up for user auth

Revision ID: 9a2d9d47d666
Revises: 1cd8d27e3863
Create Date: 2025-07-30 22:30:54.394933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2d9d47d666'
down_revision: Union[str, Sequence[str], None] = '1cd8d27e3863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ingredient_recipe_id_fkey'), 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('instruction_recipe_id_fkey'), 'instruction', type_='foreignkey')
    op.create_foreign_key(None, 'instruction', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_recipe_title'), 'recipe', ['title'], unique=False)
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'username')
    op.drop_index(op.f('ix_recipe_title'), table_name='recipe')
    op.drop_constraint(None, 'instruction', type_='foreignkey')
    op.create_foreign_key(op.f('instruction_recipe_id_fkey'), 'instruction', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key(op.f('ingredient_recipe_id_fkey'), 'ingredient', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
