"""add_theme_preference_to_user

Revision ID: 0ef69ccabb08
Revises: da406ebe251d
Create Date: 2025-08-24 15:30:59.165348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef69ccabb08'
down_revision: Union[str, Sequence[str], None] = 'da406ebe251d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    for idx in (
        'idx_ingredient_recipe_id', 'idx_instruction_recipe_id', 'idx_instruction_step_number',
        'idx_recipe_active', 'idx_recipe_favorite', 'idx_recipe_slug', 'idx_recipe_title',
        'idx_recipe_user_favorite', 'idx_recipe_user_id', 'idx_recipe_tags_recipe_id', 'idx_recipe_tags_tag_id',
        'idx_tag_name', 'idx_user_budget_preference_user_id', 'idx_user_cuisine_preference_user_id',
        'idx_user_dietary_restriction_user_id', 'idx_user_health_goal_user_id', 'idx_user_session_active',
        'idx_user_session_recipe_id', 'idx_user_session_session_id', 'idx_user_session_user_id',
        'idx_user_skill_level_user_id', 'idx_user_tag_name', 'idx_user_tag_user_id',
    ):
        conn.execute(sa.text(f'DROP INDEX IF EXISTS {idx}'))
    op.add_column('user', sa.Column('theme_preference', sa.String(), nullable=True))
    op.drop_column('user_skill_level', 'id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_tag_user_id'), 'user_tag', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_tag_name'), 'user_tag', ['tag_name'], unique=False)
    op.add_column('user_skill_level', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('idx_user_skill_level_user_id'), 'user_skill_level', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_session_session_id'), 'user_session', ['session_id'], unique=False)
    op.create_index(op.f('idx_user_session_recipe_id'), 'user_session', ['recipe_id'], unique=False)
    op.create_index(op.f('idx_user_session_active'), 'user_session', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_user_health_goal_user_id'), 'user_health_goal', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_dietary_restriction_user_id'), 'user_dietary_restriction', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_cuisine_preference_user_id'), 'user_cuisine_preference', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_budget_preference_user_id'), 'user_budget_preference', ['user_id'], unique=False)
    op.drop_column('user', 'theme_preference')
    op.create_index(op.f('idx_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('idx_recipe_tags_tag_id'), 'recipe_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_recipe_tags_recipe_id'), 'recipe_tags', ['recipe_id'], unique=False)
    op.create_index(op.f('idx_recipe_user_id'), 'recipe', ['user_id'], unique=False)
    op.create_index(op.f('idx_recipe_user_favorite'), 'recipe', ['user_id', 'favorite'], unique=False)
    op.create_index(op.f('idx_recipe_title'), 'recipe', ['title'], unique=False)
    op.create_index(op.f('idx_recipe_slug'), 'recipe', ['slug'], unique=False)
    op.create_index(op.f('idx_recipe_favorite'), 'recipe', ['favorite'], unique=False, postgresql_where='(favorite = true)')
    op.create_index(op.f('idx_recipe_active'), 'recipe', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_instruction_step_number'), 'instruction', ['recipe_id', 'step_number'], unique=False)
    op.create_index(op.f('idx_instruction_recipe_id'), 'instruction', ['recipe_id'], unique=False)
    op.create_index(op.f('idx_ingredient_recipe_id'), 'ingredient', ['recipe_id'], unique=False)
    # ### end Alembic commands ###
