"""added slug column to recipe

Revision ID: 742daed54974
Revises: 3c993a8da458
Create Date: 2025-08-04 20:27:40.185984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '742daed54974'
down_revision: Union[str, Sequence[str], None] = '3c993a8da458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_recipe_slug'), 'recipe', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_slug'), table_name='recipe')
    op.drop_column('recipe', 'slug')
    # ### end Alembic commands ###
