"""changed instruction and ingredient tables

Revision ID: cb1fe3e26b89
Revises: 9a2d9d47d666
Create Date: 2025-08-04 15:39:30.608399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1fe3e26b89'
down_revision: Union[str, Sequence[str], None] = '9a2d9d47d666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('ingredient', sa.String(), nullable=True))
    op.drop_column('ingredient', 'quantity')
    op.drop_column('ingredient', 'name')
    op.drop_column('ingredient', 'unit')
    op.drop_column('instruction', 'step_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruction', sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ingredient', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredient', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredient', sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ingredient', 'ingredient')
    # ### end Alembic commands ###
